{
  "hash": "124301361c188ef1bf48794fc0d0a79d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"How Temperature Affects Productivity in the Great Lakes\"\nauthors:\n  - name: Claire Mittel\n    affiliation: Colorado State University\n    roles: writing\n    corresponding: true\n  - name: Bailey Stender\n    affiliation: Colorado State University\n    roles: writing\n    corresponding: false\nbibliography: references.bib\ncsl: apa.csl\n---\n\n\n\n\n\n# Abstract\n\nThe Great Lakes have experienced a dramatic increase in algal blooms in recent decades due to increased nutrient runoff from over-fertilizing crops and increased inputs from industrial and municipal waste (@singh). Algal blooms can be detrimental to lake ecosystem health and result in large fish kills (@singh). Considering temperatures in this region are projected to rise due to changing climatic conditions, it is important to study the relationship between temperature and productivity levels (@mishra2010review). Since higher productivity levels in lakes usually indicate a higher level of algal blooms, this is an important measure to project because rising temperatures could put an even higher stress on lake ecosystems (@mishra2010review). Using data collected in Lake Erie and Lake Huron, measurements of productivity were identified using chlorophyll A levels. Our results indicate that there is a high to medium positive correlation between chlorophyll A levels (productivity) and temperature. Lake Erie showed a stronger relationship between chlorophyll A levels and temperature. More research is necessary to figure out why the Lake Erie data has a higher correlation between productivity and temperature compared to Lake Huron. These results highlight the need to continue studying these relationships as temperature increases due to climate change. This could inform management decisions because higher restrictions may need to be placed on nutrient inputs into the lakes.\n\n# Introduction\n\nThe topic we have chosen for our project is to see how temperature affects productivity in the Great Lakes. We are going to show the relationship by seeing how the temperature that is recorded in the lakes, Lake Erie and Lake Huron, increase or decrease the amount of Chlorophyll A. Chlorophyll A is able to show that there is high productivity in environments because it is an indicator of how much primary productivity has occurred (@baker2004chlorophyll). Primary productivity is the amount of photosynthesis that is occurring within an ecosystem. A high productivity would be indicated by a high amount of Chlorophyll A because it is what makes plants green and when they are most green, they are able to absorb the most light (@bjorn2009viewpoint). This is an important topic to be discussing because it has been shown that anthropogenic climate change has altered how much primary productivity there is in lakes. There was a study, @o2017anthropogenic, that showed that primary productivity has decreased very slowly in the last 9,000 years. Primary productivity is important to lake environments because the photosynthesis that occurs produces nutrients for consumers to thrive off of. When primary productivity goes down, the overall health of the lake goes down. Another study was done on the impact that environmental factors have on a lake in China, @shi2023impacts . This study was done over a period of 10 years and it showed that there is a strong correlation between solar radiation and chlorophyll A concentration in the summer and winter. This is important because it showed that climate change is having an impact on primary productivity of lakes through this study. The motivation behind seeing if there is a correlation between the two is that the lakes are two very different ecosystems. Another reason behind choosing this data is that Lake Erie is the most polluted of the Great Lakes. This could have an effect on how much productivity there is in the lake because there could be less light able to penetrate the water, and therefore a lower temperature for a possible lower productivity rate.\n\nThe datasets that we will be using are from the NOAA Great Lakes Environmental Research Laboratory, @lakeerie and @lakehuron. The datasets are from the same laboratory that is studying the Great Lakes and taking measurements to keep track of the water quality in each of the lakes. In Lake Erie and Lake Huron, they are keeping track of Microcystis, which is a “toxin producing algae” (@lakeerie). They are keeping track of the amount of Microcytis to see if there is a correlation between the amount of it in the water and the toxicity level in the lake. They collect other weekly environmental parameters including “nitrate (N), chlorophyll, phycocyanin, dissolved oxygen (DO), turbidity, and specific conductivity” (@lakeerie). With this data they are collecting for tracking Microcystis, they are looking to figure out what causes the algal blooms so that they are able to prepare for the harm they will cause. There was another study done about this harmful algae in Lake Erie in 2021, @qian2021chlorophyll . They found that there is a positive correlation between chlorophyll A concentration and Microcystis in Lake Erie. This work was likely used as a reason for these laboratories to study the concentration of Microcystis. Our hypothesis is that higher temperatures will result in an increase in the amount of chlorophyll A and therefore level of primary productivity in the lakes. We hypothesize this because warmer temperatures tend to increase the amount of photosynthesis that occurs (@dunstan2018global). We also hypothesize that an increase in temperature will have less of an impact on primary productivity in lake Erie because of its high pollution levels.\n\n# Methods\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(tidyr)\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ purrr     1.0.4\n✔ forcats   1.0.0     ✔ readr     2.1.5\n✔ ggplot2   3.5.1     ✔ stringr   1.5.1\n✔ lubridate 1.9.4     ✔ tibble    3.2.1\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(ggplot2)\nlakeerie <- read_csv('https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/wle-weekly-current/2024_WLE_Weekly_Datashare_CSV.csv')\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 260 Columns: 25\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (17): Date, Site, Sample_Depth_category, Sky, Secchi_Depth_m, Temp_C, S...\ndbl   (6): Station_Depth_m, Sample_Depth_m, Lat_deg, Long_deg, Wind_speed_ms...\ntime  (2): Arrival_Time, Departure_Time\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlakehuron <- read_csv('https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/sb-weekly-current/SB_Weekly_Datashare_CSV.csv')\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRows: 87 Columns: 24\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (11): Date, Site, Sample_Depth_category, Sky, Secchi_Depth_m, DO_mgL-1,...\ndbl   (9): Station_Depth_m, Sample_Depth_m, Lat_deg, Long_deg, Temp_C, SpCon...\nlgl   (2): Wind_speed_knots, Wave_Ht_ft\ntime  (2): Arrival_Time, Departure_Time\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\n\n\n\nThe data for this project was collected by NOAA’s Great Lakes Environmental Research Laboratory. This data was collected in the year 2024 between 4/24 and 10/24 for Dataset 1 (@lakeerie) and between 5/22 and 10/18 for Dataset 2 (@lakehuron). Dataset 1 contains 249 rows of data while Dataset 2 contains 82 rows of data. To clean the data, rows that have empty values will be removed. We will also only be using the columns “Temp C” and “Extracted_CHLa_ugL-1” so all other columns will be removed. \n\nMaps display where data for the two sites were collected. The data for Dataset 1 was collected in the western portion of Lake Erie at various monitoring sites (Figure 1). The white circles on the map represent the locations where samples were collected. The data for Dataset 2 was collected in Saginaw Bay, which is part of lower Lake Huron (Figure 2). \n\nSome visualizations of the data were created comparing temperature and chlorophyll concentrations using scatter plot graphs (Figure 3, 4). Before applying statistical methods, it visually looks like there is a positive correlation between temperature and chlorophyll a concentrations based on their respective trend lines.\n\n![](img/lakeeriemap.png)\n\n**Figure 1.** Map of Dataset 1 study area. White circles represent weekly monitoring collection sites, where the data we will be analyzing was collected.\n\n![](img/lakehuronmap.png)\n\n**Figure 2.** Map of Dataset 2 study area. White circles represent weekly monitoring collection sites, where the data we will be analyzing was collected\n\n![](img/lakehurontemp.png)\n\n\\\n**Figure 3.** Temperature and CHLa correlation at Lake Huron Study site (5/22-10/18)\n\n![](img/lakeerietemp.png)\n\n\\\n**Figure 4.** Temperature and CHLa correlation at Lake Erie Study site (4/24-10/24)\n\nOne method that was used in this project to determine the relationship between temperature and Chlorophyll A levels was a Chi squared test. This test helped determine if the relationship between temperature and Chlorophyll A levels were dependent on each other or not. This helped find a correlation because the expected results would be that there is no correlation and if it is different from the expected, it proves that there is a correlation. Another method that was used in this project to determine the relationship between temperature and Chlorophyll A levels is a correlation test. This helped determine if there is a linear correlation between temperature and Chlorophyll A levels by seeing if they have a strong relationship. This helped to determine what the relationship was because if there is a strong correlation, it proves that the relationship is either positive or negative. It is most likely a positive relationship because warmer temperatures tend to increase the amount of photosynthesis that occurs (@dunstan2018global). That means that an increase of photosynthesis means that there is an increase in Chlorophyll A. Therefore, there would be a positive relationship between temperature and Chlorophyll A levels.\n\nA Chi squared test was administered to test if there was a relationship between temperature and Chlorophyll A levels for each dataset. A correlation test was also used to find if there was a linear correlation between temperature and Chlorophyll A for each dataset. The two datasets themselves were tested to determine if there was a significant difference between measures of Chlorophyll A between the lakes. If data were normal and variances equal a two-sample t-test (independent t-test) was used. If data were not normal a non-parametric test was used, like the Wilcoxon Rank-Sum Test. There was also a test to find if there is a significant difference in the way temperature and Chlorophyll a interact in the different lakes. For this test a linear model was used with an interaction between lake and temperature.\n\nSome supplemental data needed for this analysis was information on why the 2 lakes may differ in Chlorophyll a levels or their relationship with Chlorophyll a and temperature. Data was needed on pollution levels to each lake. The data seemed like it would be easy to work with but Dataset 1 and Dataset 2 had a very different amount of rows. To make certain tests work we data from Dataset 1 needed to be condensed. It also was helpful to only include data from 5/22-10/18 because this is the time range of data collected in Dataset 1. Some potential challenges seem in the methods is understanding when to use certain statistical methods/making sure they are the best statistical method for the data and research question.\n\nThese selected methods helped get to our final goal because in various ways we tested the correlation between temperature and CHLa (productivity). This information will be valuable because as temperatures increase, productivity may increase and cause problems for lake ecosystems. Lake Erie to Lake Huron were also compared because pollution to lake Erie may affect productivity levels or the way temperature impacts productivity.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlakeerie2 <- lakeerie %>%\n  rename(\n    surface_temp = Temp_C,\n    chlorophyll_a = `Extracted_CHLa_ugL-1`)\nlakehuron2 <- lakehuron %>%\n  rename(\n    surface_temp = Temp_C,\n    chlorophyll_a = `Extracted_CHLa_ugL-1`)\n```\n:::\n\n\n\n\n\n# Results\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(tidyverse)\n\nlakeerie_clean <- lakeerie2 %>%\n  drop_na(surface_temp, chlorophyll_a) %>%\n  mutate(\n    surface_temp = as.numeric(surface_temp),\n    chlorophyll_a = as.numeric(chlorophyll_a))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: There was 1 warning in `mutate()`.\nℹ In argument: `surface_temp = as.numeric(surface_temp)`.\nCaused by warning:\n! NAs introduced by coercion\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlakehuron_clean <- lakehuron2 %>%\n  drop_na(surface_temp, chlorophyll_a) %>%\n  mutate(\n    surface_temp = as.numeric(surface_temp),\n    chlorophyll_a = as.numeric(chlorophyll_a))\n```\n:::\n\n\n\n\n\n### Lake Erie Tests\n\n#### Chi Squared Test\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlakeerie_binned <- lakeerie_clean %>%\n  mutate(\n    temp_cat = ntile(surface_temp, 3),\n    chl_cat = ntile(chlorophyll_a, 3)\n  ) %>%\n  mutate(\n    temp_cat = factor(temp_cat, labels = c(\"Low\", \"Medium\", \"High\")),\n    chl_cat = factor(chl_cat, labels = c(\"Low\", \"Medium\", \"High\"))\n  )\n\ntable_data <- table(lakeerie_binned$temp_cat, lakeerie_binned$chl_cat)\n\nchisq.test(table_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  table_data\nX-squared = 37.374, df = 4, p-value = 1.509e-07\n```\n\n\n:::\n:::\n\n\n\n\n\n#### Pearson's Correlation Test\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ncor.test(lakeerie_clean$surface_temp, lakeerie_clean$chlorophyll_a, method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  lakeerie_clean$surface_temp and lakeerie_clean$chlorophyll_a\nt = 6.5667, df = 247, p-value = 3.013e-10\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.2743633 0.4865281\nsample estimates:\n    cor \n0.38553 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nggplot(lakeerie_clean, aes(x = surface_temp, y = chlorophyll_a)) +\n  geom_point(color = \"blue\", alpha = 0.6) +  \n  geom_smooth(method = \"lm\", se = TRUE, color = \"red\") +  \n  labs(\n    title = \"Relationship between Surface Temperature and Chlorophyll-a in Lake Erie\",\n    x = \"Surface Temperature (°C)\",\n    y = \"Chlorophyll-a (µg/L)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 11 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Removed 11 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Figure 5:** Linear graph showing the relationship between temperature and chlorophyll A levels in Lake Erie.\n\n#### T-Test\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nchl_high <- lakeerie_binned %>% filter(temp_cat == \"High\") %>% pull(chlorophyll_a)\nchl_low  <- lakeerie_binned %>% filter(temp_cat == \"Low\") %>% pull(chlorophyll_a)\n\nt.test(chl_high, chl_low, var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  chl_high and chl_low\nt = 5.3111, df = 157.07, p-value = 3.669e-07\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n  6.586972 14.387275\nsample estimates:\nmean of x mean of y \n 23.58518  13.09806 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nchl_comparison <- lakeerie_binned %>%\n  filter(temp_cat %in% c(\"Low\", \"High\"))\n\nggplot(chl_comparison, aes(x = temp_cat, y = chlorophyll_a, fill = temp_cat)) +\n  geom_boxplot(outlier.shape = NA, alpha = 0.7, width = 0.5) +\n  geom_jitter(width = 0.15, alpha = 0.5, color = \"black\") +\n  scale_fill_manual(values = c(\"Low\" = \"#56B1F7\", \"High\" = \"#E76F51\")) +\n  labs(\n    title = \"Chlorophyll-a Levels by Surface Temperature Category in Lake Erie\",\n    subtitle = \"Welch Two-Sample t-test: High vs Low Temperature\",\n    x = \"Surface Temperature Category\",\n    y = \"Chlorophyll-a (µg/L)\",\n    fill = \"Temperature Category\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(hjust = 0.5),\n    plot.subtitle = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Figure 6:** Graph showing the relationship between high and low temperature and chlorophyll A levels in Lake Erie.\n\n### Lake Huron Tests\n\n#### Chi Squared Test\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlakehuron_binned <- lakehuron_clean %>%\n  mutate(\n    temp_cat = ntile(surface_temp, 3),\n    chl_cat = ntile(chlorophyll_a, 3)\n  ) %>%\n  mutate(\n    temp_cat = factor(temp_cat, labels = c(\"Low\", \"Medium\", \"High\")),\n    chl_cat = factor(chl_cat, labels = c(\"Low\", \"Medium\", \"High\"))\n  )\n\ntable_data <- table(lakehuron_binned$temp_cat, lakehuron_binned$chl_cat)\n\nchisq.test(table_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  table_data\nX-squared = 10.09, df = 4, p-value = 0.03894\n```\n\n\n:::\n:::\n\n\n\n\n\n#### Pearson's Correlation Test\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ncor.test(lakehuron_binned$surface_temp, lakehuron_binned$chlorophyll_a, method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  lakehuron_binned$surface_temp and lakehuron_binned$chlorophyll_a\nt = 1.65, df = 81, p-value = 0.1028\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.0367906  0.3811924\nsample estimates:\n      cor \n0.1803297 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nggplot(lakehuron_clean, aes(x = surface_temp, y = chlorophyll_a)) +\n  geom_point(color = \"blue\", alpha = 0.6) +  \n  geom_smooth(method = \"lm\", se = TRUE, color = \"red\") +  \n  labs(\n    title = \"Relationship between Surface Temperature and Chlorophyll-a in Lake Huron\",\n    x = \"Surface Temperature (°C)\",\n    y = \"Chlorophyll-a (µg/L)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Figure 7:** Linear graph showing the relationship between temperature and chlorophyll A levels in Lake Huron.\n\n#### T-Test\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nchl_high2 <- lakehuron_binned %>% filter(temp_cat == \"High\") %>% pull(chlorophyll_a)\nchl_low2  <- lakehuron_binned %>% filter(temp_cat == \"Low\") %>% pull(chlorophyll_a)\n\nt.test(chl_high2, chl_low2, var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  chl_high2 and chl_low2\nt = 2.4774, df = 48.669, p-value = 0.01676\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n  1.06416 10.21513\nsample estimates:\nmean of x mean of y \n 16.12000  10.48036 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nchl_comparison <- lakehuron_binned %>%\n  filter(temp_cat %in% c(\"Low\", \"High\"))\n\nggplot(chl_comparison, aes(x = temp_cat, y = chlorophyll_a, fill = temp_cat)) +\n  geom_boxplot(outlier.shape = NA, alpha = 0.7, width = 0.5) +\n  geom_jitter(width = 0.15, alpha = 0.5, color = \"black\") +\n  scale_fill_manual(values = c(\"Low\" = \"#56B1F7\", \"High\" = \"#E76F51\")) +\n  labs(\n    title = \"Chlorophyll-a Levels by Surface Temperature Category in Lake Huron\",\n    subtitle = \"Welch Two-Sample t-test: High vs Low Temperature\",\n    x = \"Surface Temperature Category\",\n    y = \"Chlorophyll-a (µg/L)\",\n    fill = \"Temperature Category\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(hjust = 0.5),\n    plot.subtitle = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Figure 8:** Graph showing the relationship between high and low temperature and chlorophyll A levels in Lake Huron.\n\n### Wilcox Tests\n\n#### Chlorophyll A Levels at High Temperatures in both Lakes\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nwilcox.test(chl_high, chl_high2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  chl_high and chl_high2\nW = 1458.5, p-value = 0.01907\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nchl_data <- data.frame(\n  group = factor(\n    c(rep(\"Lake Erie\", length(chl_high)), rep(\"Lake Huron\", length(chl_high2))),\n    levels = c(\"Lake Erie\", \"Lake Huron\")\n  ),\n  chlorophyll_a = c(chl_high, chl_high2)\n)\n\nggplot(chl_data, aes(x = group, y = chlorophyll_a, fill = group)) +\n  geom_violin(trim = FALSE, alpha = 0.6) +\n  geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.8) +\n  geom_jitter(width = 0.1, alpha = 0.4, color = \"black\") +\n  scale_fill_manual(values = c(\"Lake Erie\" = \"#2196F3\", \"Lake Huron\" = \"#FF7043\")) +\n  labs(\n    title = \"Comparison of Chlorophyll-a at High Temperatures Between Lake Erie and Lake Huron\",\n    subtitle = \"Wilcoxon Rank-Sum Test\",\n    x = \"Lake\",\n    y = \"Chlorophyll-a (µg/L)\"\n  ) +\n  theme_minimal(base_size = 9) +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(face = \"bold\", hjust = 0.5),\n    plot.subtitle = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Figure 9:** Graph comparing the chlorophyll A levels at high temperatures in both lakes.\n\n#### Chlorophyll A Levels at Low Temperatures in both Lakes\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nwilcox.test(chl_low, chl_low2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  chl_low and chl_low2\nW = 1281, p-value = 0.421\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nchl_data2 <- data.frame(\n  group = factor(\n    c(rep(\"Lake Erie\", length(chl_low)), rep(\"Lake Huron\", length(chl_low2))),\n    levels = c(\"Lake Erie\", \"Lake Huron\")\n  ),\n  chlorophyll_a = c(chl_low, chl_low2)\n)\n\nggplot(chl_data2, aes(x = group, y = chlorophyll_a, fill = group)) +\n  geom_violin(trim = FALSE, alpha = 0.6) +\n  geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.8) +\n  geom_jitter(width = 0.1, alpha = 0.4, color = \"black\") +\n  scale_fill_manual(values = c(\"Lake Erie\" = \"#2196F3\", \"Lake Huron\" = \"#FF7043\")) +\n  labs(\n    title = \"Comparison of Chlorophyll-a at Low Temperatures Between Lake Erie and Lake Huron\",\n    subtitle = \"Wilcoxon Rank-Sum Test\",\n    x = \"Lake\",\n    y = \"Chlorophyll-a (µg/L)\"\n  ) +\n  theme_minimal(base_size = 9) +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(face = \"bold\", hjust = 0.5),\n    plot.subtitle = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Figure 10:** Graph comparing the chlorophyll A levels at low temperatures in both lakes.\n\nThe Chi squared test that was done on the Lake Erie data (dataset 1), the p value came back as 1.509e-07. This means that there is a significant relationship between temperature and chlorophyll A levels in Lake Erie. The Pearson correlation test that was performed on the data came back with a p value of 3.013e-10. This also shows a highly significant relationship between temperature and chlorophyll A levels, which is shown in Figure 5. The T-test done also came back with a very low p value of 3.669e-16. This test also shows a high significance in the relationship of the variables. In Figure 6, the strong relationship is shown in the graph. All of these highly statistically significant results mean that high temperature has a strong relationship with chlorophyll A levels. This indicates that there is a strong relation between temperature and primary productivity in Lake Erie.\n\nThe Chi squared test that was performed on the Lake Huron data (dataset 2) the p value came back as 0.03894. This means that the data is significant and there is a relation in this data of temperature to chlorophyll A levels. The Pearson correlation test that was done on the Lake Huron data had a p value of 0.1028. This also shows that there is not a significant linear relationship between temperature and chlorophyll A levels in Lake Huron, which is shown in Figure 7. The T-test that was done on the data came back with a p value of 0.01676. This shows that there is a significant relationship between the two variables in Lake Huron in this test, which is shown in Figure 8. These statistically significant relationships show that there is a correlation between temperature and chlorophyll A levels. These statistical tests showed that there is a relationship between primary productivity and temperature, but it was not as strong of a relationship as it was in Lake Erie.\n\nThe last tests that were done were Wilcox tests on the chlorophyll A levels when the temperature is high and low in each of the lakes. The first test was on the high temperature chlorophyll A levels being compared in the lakes, which came back with a p value of 0.01907. This shows that there is a significant relationship between the two lakes' chlorophyll A levels, as you can see in Figure 9. The next test was on the low temperature chlorophyll A levels being compared in the lakes, which came back with a p value of 0.421. This shows an insignificant relationship between the chlorophyll A levels in the lakes. Figure 10 shows that there is much more variation in the levels of chlorophyll A at low temperatures than in high temperatures.\n\n# Discussion\n\nThe Lake Erie dataset showed much stronger and consistent correlation between temperature and Chlorophyll A levels. This indicates there is a high significance in the relationship between variables and chlorophyll A levels are highly dependent on temperature. For the Lake Huron dataset, the p-value for the chi-squared test came back as significant while the value for the Pearson Correlation test indicates there was not a significant relationship between temperature and chlorophyll A. Since a chi-test measures association between categorical variables, continuous data is sorted into categories. This suggests there is a non-random association between the categories (high temperature and high chlorophyll A concentration for example). The Pearson correlation tests the strength and direction of the linear relationship between two continuous variables. This indicates that the relationship may not be linear, but could be curved, thresholded or influenced by other variables the Pearson Correlation test cannot detect.\n\nThese findings imply that temperature and chlorophyll A have a positive identifiable correlation. Since chlorophyll A is an indicator of high levels of algae productivity, this suggests that when temperatures increase, algal blooms also increase. Large algal blooms can be detrimental to lake ecosystem health. It is helpful to study this relationship because as temperatures increase with climate change, this might increase the level of harmful algal blooms in lake ecosystems. This could influence management decisions and the regulation of pollutants or nutrient input to the great lakes. \n\nOne possible reason for why Lake Erie had much stronger results for temperature and chlorophyll A levels is because it is the most polluted lake of the Great Lakes (@wood1968pollution). Because it is more polluted than other lakes, it is more susceptible to eutrophication. Eutrophication in lakes occurs when there is an offloading of nutrients into the lake which feeds the algae there, causing large, harmful blooms. This usually comes from agricultural runoff from the fertilizer that is used. Lake Erie is particularly vulnerable to this happening quicker because it has much less volume than other Great Lakes (@wood1968pollution). Lake Erie also has much more agricultural runoff coming into it (@watson2016re). This makes it much more vulnerable to large algal growths that can be harmful to the lake ecosystem's health.\n\nAnother reason why Lake Erie had much stronger results is because there were several more points of data that were collected and used in the analysis. As you can see in Figures 5 and 6, there are several points of data and in Figures 7 and 8, there are far less than the previous ones. This could have created more variation in the results since there are less points of data. This could have caused it to be less precise with more room for error. This room for error is displayed the most in Figures 9 and 10, because the bubble around the box plot for Lake Huron that is representing the standard of error is much wider than Lake Erie's. The difference in the number of data points is also very clear in these two figures because side by side there is a very clear disparity in the number of data points in Lake Erie and Lake Huron.\n\nThis analysis is very limited because the data used in these statistical tests were collected only during one year. This means that these statistical tests did not account for variation of different factors between years such as climate, nutrient input, and other factors. There was also a fairly small sample size which could have skewed the results. The next steps proposed are to conduct a much longer term study that spans multiple years to account for the variation between years and measure how increasing temperatures are changing chlorophyll A concentration. Using different study sites on different lakes or different parts of the lakes could also give a more comprehensive picture of this relationship.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}