<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
    <meta charset="utf-8">
    <meta name="generator" content="quarto-1.5.57">

    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


    <title>How Temperature Affects Productivity in the Great Lakes</title>
    <style>
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      div.columns{display: flex; gap: min(4vw, 1.5em);}
      div.column{flex: auto; overflow-x: auto;}
      div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
      ul.task-list{list-style: none;}
      ul.task-list li input[type="checkbox"] {
        width: 0.8em;
        margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
        vertical-align: middle;
      }
      /* CSS for syntax highlighting */
      pre > code.sourceCode { white-space: pre; position: relative; }
      pre > code.sourceCode > span { line-height: 1.25; }
      pre > code.sourceCode > span:empty { height: 1.2em; }
      .sourceCode { overflow: visible; }
      code.sourceCode > span { color: inherit; text-decoration: inherit; }
      div.sourceCode { margin: 1em 0; }
      pre.sourceCode { margin: 0; }
      @media screen {
      div.sourceCode { overflow: auto; }
      }
      @media print {
      pre > code.sourceCode { white-space: pre-wrap; }
      pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
      }
      pre.numberSource code
        { counter-reset: source-line 0; }
      pre.numberSource code > span
        { position: relative; left: -4em; counter-increment: source-line; }
      pre.numberSource code > span > a:first-child::before
        { content: counter(source-line);
          position: relative; left: -1em; text-align: right; vertical-align: baseline;
          border: none; display: inline-block;
          -webkit-touch-callout: none; -webkit-user-select: none;
          -khtml-user-select: none; -moz-user-select: none;
          -ms-user-select: none; user-select: none;
          padding: 0 4px; width: 4em;
        }
      pre.numberSource { margin-left: 3em;  padding-left: 4px; }
      div.sourceCode
        {   }
      @media screen {
      pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
      }
      /* CSS for citations */
      div.csl-bib-body { }
      div.csl-entry {
        clear: both;
        margin-bottom: 0em;
      }
      .hanging-indent div.csl-entry {
        margin-left:2em;
        text-indent:-2em;
      }
      div.csl-left-margin {
        min-width:2em;
        float:left;
      }
      div.csl-right-inline {
        margin-left:2em;
        padding-left:1em;
      }
      div.csl-indent {
        margin-left: 2em;
      }    </style>

    <style>
      body.hypothesis-enabled #quarto-embed-header {
        padding-right: 36px;
      }

      #quarto-embed-header {
        height: 3em;
        width: 100%;
        display: flex;
        justify-content: space-between;
        align-items: center;
        border-bottom: solid 1px;
      }

      #quarto-embed-header h6 {
        font-size: 1.1em;
        padding-top: 0.6em;
        margin-left: 1em;
        margin-right: 1em;
        font-weight: 400;
      }

      #quarto-embed-header a.quarto-back-link,
      #quarto-embed-header a.quarto-download-embed {
        font-size: 0.8em;
        margin-top: 1em;
        margin-bottom: 1em;
        margin-left: 1em;
        margin-right: 1em;
      }

      .quarto-back-container {
        padding-left: 0.5em;
        display: flex;
      }

      .headroom {
          will-change: transform;
          transition: transform 200ms linear;
      }

      .headroom--pinned {
          transform: translateY(0%);
      }

      .headroom--unpinned {
          transform: translateY(-100%);
      }      
    </style>

    <script>
    window.document.addEventListener("DOMContentLoaded", function () {

      var header = window.document.querySelector("#quarto-embed-header");
      const titleBannerEl = window.document.querySelector("body > #title-block-header");
      if (titleBannerEl) {
        titleBannerEl.style.paddingTop = header.clientHeight + "px";
      }
      const contentEl = window.document.getElementById('quarto-content');
      for (const child of contentEl.children) {
        child.style.paddingTop = header.clientHeight + "px";
        child.style.marginTop = "1em";
      }

      // Use the article root if the `back` call doesn't work. This isn't perfect
      // but should typically work
      window.quartoBackToArticle = () => {
        var currentUrl = window.location.href;
        window.history.back();
        setTimeout(() => {
            // if location was not changed in 100 ms, then there is no history back
            if(currentUrl === window.location.href){              
                // redirect to site root
                window.location.href = "index.html";
            }
        }, 100);
      }

      const headroom = new window.Headroom(header, {
        tolerance: 5,
        onPin: function () {
        },
        onUnpin: function () {
        },
      });
      headroom.init();
    });
    </script>

    
<script src="site_libs/manuscript-notebook/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
     <script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>  
      <meta name="citation_title" content="How Temperature Affects Productivity in the Great Lakes">
<meta name="citation_author" content="Claire Mittel">
<meta name="citation_author" content="Bailey Stender">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Literate programming;,citation_author=Donald E. Knuth;,citation_publication_date=1984-05;,citation_cover_date=1984-05;,citation_year=1984;,citation_fulltext_html_url=https://doi.org/10.1093/comjnl/27.2.97;,citation_issue=2;,citation_doi=10.1093/comjnl/27.2.97;,citation_issn=0010-4620;,citation_volume=27;,citation_journal_title=Comput. J.;,citation_publisher=Oxford University Press, Inc.;">
<meta name="citation_reference" content="citation_title=Chlorophyll fluorescence as a probe of photosynthetic productivity;,citation_author=Neil R Baker;,citation_author=Kevin Oxborough;,citation_publication_date=2004;,citation_cover_date=2004;,citation_year=2004;,citation_inbook_title=Chlorophyll a fluorescence: A signature of photosynthesis;">
<meta name="citation_reference" content="citation_title=A viewpoint: Why chlorophyll a?;,citation_author=Lars Olof Björn;,citation_author=George C Papageorgiou;,citation_author=Robert E Blankenship;,citation_author=undefined Govindjee;,citation_publication_date=2009;,citation_cover_date=2009;,citation_year=2009;,citation_volume=99;,citation_journal_title=Photosynthesis research;,citation_publisher=Springer;">
<meta name="citation_reference" content="citation_title=Global patterns of change and variation in sea surface temperature and chlorophyll a;,citation_author=Piers K Dunstan;,citation_author=Scott D Foster;,citation_author=Edward King;,citation_author=James Risbey;,citation_author=Terence J O’Kane;,citation_author=Didier Monselesan;,citation_author=Alistair J Hobday;,citation_author=Jason R Hartog;,citation_author=Peter A Thompson;,citation_publication_date=2018;,citation_cover_date=2018;,citation_year=2018;,citation_issue=1;,citation_volume=8;,citation_journal_title=Scientific reports;,citation_publisher=Nature Publishing Group UK London;">
<meta name="citation_reference" content="citation_title=NOAA-glerl western lake erie sampling data;,citation_author=NOAA US Department of Commerce;,citation_fulltext_html_url=https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/wle-weekly-current/;,citation_journal_title=Home: NOAA Great Lakes Environmental Research Laboratory - Ann Arbor, MI, USA;">
<meta name="citation_reference" content="citation_title=NOAA-glerl saginaw bay sampling data;,citation_author=NOAA US Department of Commerce;,citation_fulltext_html_url=https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/sb-weekly-current/;,citation_journal_title=Home: NOAA Great Lakes Environmental Research Laboratory - Ann Arbor, MI, USA;">
<meta name="citation_reference" content="citation_title=Anthropogenic climate change has altered primary productivity in lake superior;,citation_author=MD O’Beirne;,citation_author=JP Werne;,citation_author=RE Hecky;,citation_author=TC Johnson;,citation_author=Sergei Katsev;,citation_author=Euan D Reavie;,citation_publication_date=2017;,citation_cover_date=2017;,citation_year=2017;,citation_issue=1;,citation_volume=8;,citation_journal_title=Nature communications;,citation_publisher=Nature Publishing Group UK London;">
<meta name="citation_reference" content="citation_title=Pollution and lake erie;,citation_author=Kenneth G Wood;,citation_publication_date=1968;,citation_cover_date=1968;,citation_year=1968;,citation_journal_title=Bios;,citation_publisher=JSTOR;">
<meta name="citation_reference" content="citation_title=The re-eutrophication of lake erie: Harmful algal blooms and hypoxia;,citation_author=Susan B Watson;,citation_author=Carol Miller;,citation_author=George Arhonditsis;,citation_author=Gregory L Boyer;,citation_author=Wayne Carmichael;,citation_author=Murray N Charlton;,citation_author=Remegio Confesor;,citation_author=David C Depew;,citation_author=Tomas O Höök;,citation_author=Stuart A Ludsin;,citation_author=others;,citation_publication_date=2016;,citation_cover_date=2016;,citation_year=2016;,citation_volume=56;,citation_journal_title=Harmful algae;,citation_publisher=Elsevier;">
<meta name="citation_reference" content="citation_title=Chlorophyll a as an indicator of microcystin: Short-term forecasting and risk assessment in lake erie;,citation_author=Song S Qian;,citation_author=Craig A Stow;,citation_author=Freya E Rowland;,citation_author=Qianqian Liu;,citation_author=Mark D Rowe;,citation_author=Eric J Anderson;,citation_author=Richard P Stumpf;,citation_author=Thomas H Johengen;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_volume=130;,citation_journal_title=Ecological Indicators;,citation_publisher=Elsevier;">
<meta name="citation_reference" content="citation_title=Impacts of environmental factors on chlorophyll-a in lakes in cold and arid regions: A 10-year study of wuliangsuhai lake, china;,citation_author=Xiaohong Shi;,citation_author=Haifeng Yu;,citation_author=Shengnan Zhao;,citation_author=Biao Sun;,citation_author=Yu Liu;,citation_author=Jingbo Huo;,citation_author=Shihuan Wang;,citation_author=Jialin Wang;,citation_author=Yue Wu;,citation_author=Yi Wang;,citation_author=others;,citation_publication_date=2023;,citation_cover_date=2023;,citation_year=2023;,citation_volume=148;,citation_journal_title=Ecological Indicators;,citation_publisher=Elsevier;">
<meta name="citation_reference" content="citation_title=Nutrients, eutrophication and harmful algal blooms along the freshwater to marine continuum;,citation_abstract=Abstract Agricultural, urban and industrial activities have dramatically increased aquatic nitrogen and phosphorus pollution (eutrophication), threatening water quality and biotic integrity from headwater streams to coastal areas world-wide. Eutrophication creates multiple problems, including hypoxic “dead zones” that reduce fish and shellfish production; harmful algal blooms that create taste and odor problems and threaten the safety of drinking water and aquatic food supplies; stimulation of greenhouse gas releases; and degradation of cultural and social values of these waters. Conservative estimates of annual costs of eutrophication have indicated $1 billion losses for European coastal waters and $2.4 billion for lakes and streams in the United States. Scientists have debated whether phosphorus, nitrogen, or both need to be reduced to control eutrophication along the freshwater to marine continuum, but many management agencies worldwide are increasingly opting for dual control. The unidirectional flow of water and nutrients through streams, rivers, lakes, estuaries and ultimately coastal oceans adds additional complexity, as each of these ecosystems may be limited by different factors. Consequently, the reduction of just one nutrient upstream to control eutrophication can allow the export of other nutrients downstream where they may stimulate algal production. The technology exists for controlling eutrophication, but many challenges remain for understanding and managing this global environmental problem. This article is categorized under: Science of Water &amp;amp;amp;gt; Water Quality Water and Life &amp;gt; Stresses and Pressures on Ecosystems;,citation_author=Wayne A. Wurtsbaugh;,citation_author=Hans W. Paerl;,citation_author=Walter K. Dodds;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_fulltext_html_url=https://wires.onlinelibrary.wiley.com/doi/abs/10.1002/wat2.1373;,citation_issue=5;,citation_doi=https://doi.org/10.1002/wat2.1373;,citation_volume=6;,citation_journal_title=WIREs Water;">
<meta name="citation_reference" content="citation_title=A review of drought concepts;,citation_author=Ashok K Mishra;,citation_author=Vijay P Singh;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;,citation_issue=1-2;,citation_volume=391;,citation_journal_title=Journal of hydrology;,citation_publisher=Elsevier;">
</head>

  <body class="quarto-notebook">
    <div id="quarto-embed-header" class="headroom fixed-top bg-primary">
      
      <a onclick="window.quartoBackToArticle(); return false;" class="btn btn-primary quarto-back-link" href=""><i class="bi bi-caret-left"></i> Back to Article</a>
      <h6><i class="bi bi-journal-code"></i> Article Notebook</h6>

            <a href="./index.qmd" class="btn btn-primary quarto-download-embed" download="index.qmd">Download Source</a>
          </div>

     <header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">How Temperature Affects Productivity in the Great Lakes</h1>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
            <div class="quarto-title-meta-author">
          <div class="quarto-title-meta-heading">Authors</div>
          <div class="quarto-title-meta-heading">Affiliation</div>
          
                <div class="quarto-title-meta-contents">
            <p class="author">Claire Mittel </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Colorado State University
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">Bailey Stender </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Colorado State University
                      </p>
                  </div>
                    </div>
        
        <div class="quarto-title-meta">

                      
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      </div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#lake-erie-tests" id="toc-lake-erie-tests" class="nav-link" data-scroll-target="#lake-erie-tests">Lake Erie Tests</a></li>
  <li><a href="#lake-huron-tests" id="toc-lake-huron-tests" class="nav-link" data-scroll-target="#lake-huron-tests">Lake Huron Tests</a></li>
  <li><a href="#wilcox-tests" id="toc-wilcox-tests" class="nav-link" data-scroll-target="#wilcox-tests">Wilcox Tests</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">      

       <section id="abstract" class="level1">
<h1>Abstract</h1>
<p>The Great Lakes have experienced a dramatic increase in algal blooms in recent decades due to increased nutrient runoff from over-fertilizing crops and increased inputs from industrial and municipal waste (<span class="citation" data-cites="singh">Wurtsbaugh et al. (<a href="#ref-singh" role="doc-biblioref">2019</a>)</span>). Algal blooms can be detrimental to lake ecosystem health and result in large fish kills (<span class="citation" data-cites="singh">Wurtsbaugh et al. (<a href="#ref-singh" role="doc-biblioref">2019</a>)</span>). Considering temperatures in this region are projected to rise due to changing climatic conditions, it is important to study the relationship between temperature and productivity levels (<span class="citation" data-cites="mishra2010review">Mishra &amp; Singh (<a href="#ref-mishra2010review" role="doc-biblioref">2010</a>)</span>). Since higher productivity levels in lakes usually indicate a higher level of algal blooms, this is an important measure to project because rising temperatures could put an even higher stress on lake ecosystems (<span class="citation" data-cites="mishra2010review">Mishra &amp; Singh (<a href="#ref-mishra2010review" role="doc-biblioref">2010</a>)</span>). Using data collected in Lake Erie and Lake Huron, measurements of productivity were identified using chlorophyll A levels. Our results indicate that there is a high to medium positive correlation between chlorophyll A levels (productivity) and temperature. Lake Erie showed a stronger relationship between chlorophyll A levels and temperature. More research is necessary to figure out why the Lake Erie data has a higher correlation between productivity and temperature compared to Lake Huron. These results highlight the need to continue studying these relationships as temperature increases due to climate change. This could inform management decisions because higher restrictions may need to be placed on nutrient inputs into the lakes.</p>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The topic we have chosen for our project is to see how temperature affects productivity in the Great Lakes. We are going to show the relationship by seeing how the temperature that is recorded in the lakes, Lake Erie and Lake Huron, increase or decrease the amount of Chlorophyll A. Chlorophyll A is able to show that there is high productivity in environments because it is an indicator of how much primary productivity has occurred (<span class="citation" data-cites="baker2004chlorophyll">Baker &amp; Oxborough (<a href="#ref-baker2004chlorophyll" role="doc-biblioref">2004</a>)</span>). Primary productivity is the amount of photosynthesis that is occurring within an ecosystem. A high productivity would be indicated by a high amount of Chlorophyll A because it is what makes plants green and when they are most green, they are able to absorb the most light (<span class="citation" data-cites="bjorn2009viewpoint">Björn et al. (<a href="#ref-bjorn2009viewpoint" role="doc-biblioref">2009</a>)</span>). This is an important topic to be discussing because it has been shown that anthropogenic climate change has altered how much primary productivity there is in lakes. There was a study, <span class="citation" data-cites="o2017anthropogenic">O’Beirne et al. (<a href="#ref-o2017anthropogenic" role="doc-biblioref">2017</a>)</span>, that showed that primary productivity has decreased very slowly in the last 9,000 years. Primary productivity is important to lake environments because the photosynthesis that occurs produces nutrients for consumers to thrive off of. When primary productivity goes down, the overall health of the lake goes down. Another study was done on the impact that environmental factors have on a lake in China, <span class="citation" data-cites="shi2023impacts">Shi et al. (<a href="#ref-shi2023impacts" role="doc-biblioref">2023</a>)</span> . This study was done over a period of 10 years and it showed that there is a strong correlation between solar radiation and chlorophyll A concentration in the summer and winter. This is important because it showed that climate change is having an impact on primary productivity of lakes through this study. The motivation behind seeing if there is a correlation between the two is that the lakes are two very different ecosystems. Another reason behind choosing this data is that Lake Erie is the most polluted of the Great Lakes. This could have an effect on how much productivity there is in the lake because there could be less light able to penetrate the water, and therefore a lower temperature for a possible lower productivity rate.</p>
<p>The datasets that we will be using are from the NOAA Great Lakes Environmental Research Laboratory, <span class="citation" data-cites="lakeerie">US Department of Commerce (<a href="#ref-lakeerie" role="doc-biblioref">n.d.-b</a>)</span> and <span class="citation" data-cites="lakehuron">US Department of Commerce (<a href="#ref-lakehuron" role="doc-biblioref">n.d.-a</a>)</span>. The datasets are from the same laboratory that is studying the Great Lakes and taking measurements to keep track of the water quality in each of the lakes. In Lake Erie and Lake Huron, they are keeping track of Microcystis, which is a “toxin producing algae” (<span class="citation" data-cites="lakeerie">US Department of Commerce (<a href="#ref-lakeerie" role="doc-biblioref">n.d.-b</a>)</span>). They are keeping track of the amount of Microcytis to see if there is a correlation between the amount of it in the water and the toxicity level in the lake. They collect other weekly environmental parameters including “nitrate (N), chlorophyll, phycocyanin, dissolved oxygen (DO), turbidity, and specific conductivity” (<span class="citation" data-cites="lakeerie">US Department of Commerce (<a href="#ref-lakeerie" role="doc-biblioref">n.d.-b</a>)</span>). With this data they are collecting for tracking Microcystis, they are looking to figure out what causes the algal blooms so that they are able to prepare for the harm they will cause. There was another study done about this harmful algae in Lake Erie in 2021, <span class="citation" data-cites="qian2021chlorophyll">Qian et al. (<a href="#ref-qian2021chlorophyll" role="doc-biblioref">2021</a>)</span> . They found that there is a positive correlation between chlorophyll A concentration and Microcystis in Lake Erie. This work was likely used as a reason for these laboratories to study the concentration of Microcystis. Our hypothesis is that higher temperatures will result in an increase in the amount of chlorophyll A and therefore level of primary productivity in the lakes. We hypothesize this because warmer temperatures tend to increase the amount of photosynthesis that occurs (<span class="citation" data-cites="dunstan2018global">Dunstan et al. (<a href="#ref-dunstan2018global" role="doc-biblioref">2018</a>)</span>). We also hypothesize that an increase in temperature will have less of an impact on primary productivity in lake Erie because of its high pollution levels.</p>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<div class="cell-container"><div class="cell-decorator"><pre>In [1]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ purrr     1.0.4
✔ forcats   1.0.0     ✔ readr     2.1.5
✔ ggplot2   3.5.1     ✔ stringr   1.5.1
✔ lubridate 1.9.4     ✔ tibble    3.2.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>lakeerie <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/wle-weekly-current/2024_WLE_Weekly_Datashare_CSV.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 260 Columns: 25
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (17): Date, Site, Sample_Depth_category, Sky, Secchi_Depth_m, Temp_C, S...
dbl   (6): Station_Depth_m, Sample_Depth_m, Lat_deg, Long_deg, Wind_speed_ms...
time  (2): Arrival_Time, Departure_Time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>lakehuron <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/sb-weekly-current/SB_Weekly_Datashare_CSV.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 87 Columns: 24
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (11): Date, Site, Sample_Depth_category, Sky, Secchi_Depth_m, DO_mgL-1,...
dbl   (9): Station_Depth_m, Sample_Depth_m, Lat_deg, Long_deg, Temp_C, SpCon...
lgl   (2): Wind_speed_knots, Wave_Ht_ft
time  (2): Arrival_Time, Departure_Time

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div></div>
<p>The data for this project was collected by NOAA’s Great Lakes Environmental Research Laboratory. This data was collected in the year 2024 between 4/24 and 10/24 for Dataset 1 (<span class="citation" data-cites="lakeerie">US Department of Commerce (<a href="#ref-lakeerie" role="doc-biblioref">n.d.-b</a>)</span>) and between 5/22 and 10/18 for Dataset 2 (<span class="citation" data-cites="lakehuron">US Department of Commerce (<a href="#ref-lakehuron" role="doc-biblioref">n.d.-a</a>)</span>). Dataset 1 contains 249 rows of data while Dataset 2 contains 82 rows of data. To clean the data, rows that have empty values will be removed. We will also only be using the columns “Temp C” and “Extracted_CHLa_ugL-1” so all other columns will be removed.&nbsp;</p>
<p>Maps display where data for the two sites were collected. The data for Dataset 1 was collected in the western portion of Lake Erie at various monitoring sites (Figure 1). The white circles on the map represent the locations where samples were collected. The data for Dataset 2 was collected in Saginaw Bay, which is part of lower Lake Huron (Figure 2).&nbsp;</p>
<p>Some visualizations of the data were created comparing temperature and chlorophyll concentrations using scatter plot graphs (Figure 3, 4). Before applying statistical methods, it visually looks like there is a positive correlation between temperature and chlorophyll a concentrations based on their respective trend lines.</p>
<p><a href="img/lakeeriemap.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="img/lakeeriemap.png" class="img-fluid"></a></p>
<p><strong>Figure 1.</strong> Map of Dataset 1 study area. White circles represent weekly monitoring collection sites, where the data we will be analyzing was collected.</p>
<p><a href="img/lakehuronmap.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="img/lakehuronmap.png" class="img-fluid"></a></p>
<p><strong>Figure 2.</strong> Map of Dataset 2 study area. White circles represent weekly monitoring collection sites, where the data we will be analyzing was collected</p>
<p><a href="img/lakehurontemp.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="img/lakehurontemp.png" class="img-fluid"></a></p>
<p><br>
<strong>Figure 3.</strong> Temperature and CHLa correlation at Lake Huron Study site (5/22-10/18)</p>
<p><a href="img/lakeerietemp.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="img/lakeerietemp.png" class="img-fluid"></a></p>
<p><br>
<strong>Figure 4.</strong> Temperature and CHLa correlation at Lake Erie Study site (4/24-10/24)</p>
<p>One method that was used in this project to determine the relationship between temperature and Chlorophyll A levels was a Chi squared test. This test helped determine if the relationship between temperature and Chlorophyll A levels were dependent on each other or not. This helped find a correlation because the expected results would be that there is no correlation and if it is different from the expected, it proves that there is a correlation. Another method that was used in this project to determine the relationship between temperature and Chlorophyll A levels is a correlation test. This helped determine if there is a linear correlation between temperature and Chlorophyll A levels by seeing if they have a strong relationship. This helped to determine what the relationship was because if there is a strong correlation, it proves that the relationship is either positive or negative. It is most likely a positive relationship because warmer temperatures tend to increase the amount of photosynthesis that occurs (<span class="citation" data-cites="dunstan2018global">Dunstan et al. (<a href="#ref-dunstan2018global" role="doc-biblioref">2018</a>)</span>). That means that an increase of photosynthesis means that there is an increase in Chlorophyll A. Therefore, there would be a positive relationship between temperature and Chlorophyll A levels.</p>
<p>A Chi squared test was administered to test if there was a relationship between temperature and Chlorophyll A levels for each dataset. A correlation test was also used to find if there was a linear correlation between temperature and Chlorophyll A for each dataset. The two datasets themselves were tested to determine if there was a significant difference between measures of Chlorophyll A between the lakes. If data were normal and variances equal a two-sample t-test (independent t-test) was used. If data were not normal a non-parametric test was used, like the Wilcoxon Rank-Sum Test. There was also a test to find if there is a significant difference in the way temperature and Chlorophyll a interact in the different lakes. For this test a linear model was used with an interaction between lake and temperature.</p>
<p>Some supplemental data needed for this analysis was information on why the 2 lakes may differ in Chlorophyll a levels or their relationship with Chlorophyll a and temperature. Data was needed on pollution levels to each lake. The data seemed like it would be easy to work with but Dataset 1 and Dataset 2 had a very different amount of rows. To make certain tests work we data from Dataset 1 needed to be condensed. It also was helpful to only include data from 5/22-10/18 because this is the time range of data collected in Dataset 1. Some potential challenges seem in the methods is understanding when to use certain statistical methods/making sure they are the best statistical method for the data and research question.</p>
<p>These selected methods helped get to our final goal because in various ways we tested the correlation between temperature and CHLa (productivity). This information will be valuable because as temperatures increase, productivity may increase and cause problems for lake ecosystems. Lake Erie to Lake Huron were also compared because pollution to lake Erie may affect productivity levels or the way temperature impacts productivity.</p>
<div class="cell-container"><div class="cell-decorator"><pre>In [2]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>lakeerie2 <span class="ot">&lt;-</span> lakeerie <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">surface_temp =</span> Temp_C,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">chlorophyll_a =</span> <span class="st">`</span><span class="at">Extracted_CHLa_ugL-1</span><span class="st">`</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>lakehuron2 <span class="ot">&lt;-</span> lakehuron <span class="sc">%&gt;%</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">surface_temp =</span> Temp_C,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">chlorophyll_a =</span> <span class="st">`</span><span class="at">Extracted_CHLa_ugL-1</span><span class="st">`</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<div class="cell-container"><div class="cell-decorator"><pre>In [3]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>lakeerie_clean <span class="ot">&lt;-</span> lakeerie2 <span class="sc">%&gt;%</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(surface_temp, chlorophyll_a) <span class="sc">%&gt;%</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">surface_temp =</span> <span class="fu">as.numeric</span>(surface_temp),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">chlorophyll_a =</span> <span class="fu">as.numeric</span>(chlorophyll_a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `surface_temp = as.numeric(surface_temp)`.
Caused by warning:
! NAs introduced by coercion</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>lakehuron_clean <span class="ot">&lt;-</span> lakehuron2 <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(surface_temp, chlorophyll_a) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">surface_temp =</span> <span class="fu">as.numeric</span>(surface_temp),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">chlorophyll_a =</span> <span class="fu">as.numeric</span>(chlorophyll_a))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div>
<section id="lake-erie-tests" class="level3">
<h3 class="anchored" data-anchor-id="lake-erie-tests">Lake Erie Tests</h3>
<section id="chi-squared-test" class="level4">
<h4 class="anchored" data-anchor-id="chi-squared-test">Chi Squared Test</h4>
<div class="cell-container"><div class="cell-decorator"><pre>In [4]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>lakeerie_binned <span class="ot">&lt;-</span> lakeerie_clean <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">temp_cat =</span> <span class="fu">ntile</span>(surface_temp, <span class="dv">3</span>),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">chl_cat =</span> <span class="fu">ntile</span>(chlorophyll_a, <span class="dv">3</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">temp_cat =</span> <span class="fu">factor</span>(temp_cat, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span>)),</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">chl_cat =</span> <span class="fu">factor</span>(chl_cat, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span>))</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>table_data <span class="ot">&lt;-</span> <span class="fu">table</span>(lakeerie_binned<span class="sc">$</span>temp_cat, lakeerie_binned<span class="sc">$</span>chl_cat)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(table_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table_data
X-squared = 37.374, df = 4, p-value = 1.509e-07</code></pre>
</div>
</div></div>
</section>
<section id="pearsons-correlation-test" class="level4">
<h4 class="anchored" data-anchor-id="pearsons-correlation-test">Pearson’s Correlation Test</h4>
<div class="cell-container"><div class="cell-decorator"><pre>In [5]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(lakeerie_clean<span class="sc">$</span>surface_temp, lakeerie_clean<span class="sc">$</span>chlorophyll_a, <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  lakeerie_clean$surface_temp and lakeerie_clean$chlorophyll_a
t = 6.5667, df = 247, p-value = 3.013e-10
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.2743633 0.4865281
sample estimates:
    cor 
0.38553 </code></pre>
</div>
</div></div>
<div class="cell-container"><div class="cell-decorator"><pre>In [6]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(lakeerie_clean, <span class="fu">aes</span>(<span class="at">x =</span> surface_temp, <span class="at">y =</span> chlorophyll_a)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span>  </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span>  </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship between Surface Temperature and Chlorophyll-a in Lake Erie"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Surface Temperature (°C)"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Chlorophyll-a (µg/L)"</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 11 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 11 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="">
<figure class="figure">
<p class=""><a href="index_files/figure-html/unnamed-chunk-6-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div></div>
<p><strong>Figure 5:</strong> Linear graph showing the relationship between temperature and chlorophyll A levels in Lake Erie.</p>
</section>
<section id="t-test" class="level4">
<h4 class="anchored" data-anchor-id="t-test">T-Test</h4>
<div class="cell-container"><div class="cell-decorator"><pre>In [7]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>chl_high <span class="ot">&lt;-</span> lakeerie_binned <span class="sc">%&gt;%</span> <span class="fu">filter</span>(temp_cat <span class="sc">==</span> <span class="st">"High"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(chlorophyll_a)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>chl_low  <span class="ot">&lt;-</span> lakeerie_binned <span class="sc">%&gt;%</span> <span class="fu">filter</span>(temp_cat <span class="sc">==</span> <span class="st">"Low"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(chlorophyll_a)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(chl_high, chl_low, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  chl_high and chl_low
t = 5.3111, df = 157.07, p-value = 3.669e-07
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
  6.586972 14.387275
sample estimates:
mean of x mean of y 
 23.58518  13.09806 </code></pre>
</div>
</div></div>
<div class="cell-container"><div class="cell-decorator"><pre>In [8]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>chl_comparison <span class="ot">&lt;-</span> lakeerie_binned <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(temp_cat <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"High"</span>))</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chl_comparison, <span class="fu">aes</span>(<span class="at">x =</span> temp_cat, <span class="at">y =</span> chlorophyll_a, <span class="at">fill =</span> temp_cat)) <span class="sc">+</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.15</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Low"</span> <span class="ot">=</span> <span class="st">"#56B1F7"</span>, <span class="st">"High"</span> <span class="ot">=</span> <span class="st">"#E76F51"</span>)) <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Chlorophyll-a Levels by Surface Temperature Category in Lake Erie"</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Welch Two-Sample t-test: High vs Low Temperature"</span>,</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Surface Temperature Category"</span>,</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Chlorophyll-a (µg/L)"</span>,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Temperature Category"</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="">
<figure class="figure">
<p class=""><a href="index_files/figure-html/unnamed-chunk-8-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div></div>
<p><strong>Figure 6:</strong> Graph showing the relationship between high and low temperature and chlorophyll A levels in Lake Erie.</p>
</section>
</section>
<section id="lake-huron-tests" class="level3">
<h3 class="anchored" data-anchor-id="lake-huron-tests">Lake Huron Tests</h3>
<section id="chi-squared-test-1" class="level4">
<h4 class="anchored" data-anchor-id="chi-squared-test-1">Chi Squared Test</h4>
<div class="cell-container"><div class="cell-decorator"><pre>In [9]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>lakehuron_binned <span class="ot">&lt;-</span> lakehuron_clean <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">temp_cat =</span> <span class="fu">ntile</span>(surface_temp, <span class="dv">3</span>),</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">chl_cat =</span> <span class="fu">ntile</span>(chlorophyll_a, <span class="dv">3</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">temp_cat =</span> <span class="fu">factor</span>(temp_cat, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span>)),</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">chl_cat =</span> <span class="fu">factor</span>(chl_cat, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span>))</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>table_data <span class="ot">&lt;-</span> <span class="fu">table</span>(lakehuron_binned<span class="sc">$</span>temp_cat, lakehuron_binned<span class="sc">$</span>chl_cat)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(table_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table_data
X-squared = 10.09, df = 4, p-value = 0.03894</code></pre>
</div>
</div></div>
</section>
<section id="pearsons-correlation-test-1" class="level4">
<h4 class="anchored" data-anchor-id="pearsons-correlation-test-1">Pearson’s Correlation Test</h4>
<div class="cell-container"><div class="cell-decorator"><pre>In [10]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(lakehuron_binned<span class="sc">$</span>surface_temp, lakehuron_binned<span class="sc">$</span>chlorophyll_a, <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  lakehuron_binned$surface_temp and lakehuron_binned$chlorophyll_a
t = 1.65, df = 81, p-value = 0.1028
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.0367906  0.3811924
sample estimates:
      cor 
0.1803297 </code></pre>
</div>
</div></div>
<div class="cell-container"><div class="cell-decorator"><pre>In [11]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(lakehuron_clean, <span class="fu">aes</span>(<span class="at">x =</span> surface_temp, <span class="at">y =</span> chlorophyll_a)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span>  </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span>  </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relationship between Surface Temperature and Chlorophyll-a in Lake Huron"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Surface Temperature (°C)"</span>,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Chlorophyll-a (µg/L)"</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="">
<figure class="figure">
<p class=""><a href="index_files/figure-html/unnamed-chunk-11-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div></div>
<p><strong>Figure 7:</strong> Linear graph showing the relationship between temperature and chlorophyll A levels in Lake Huron.</p>
</section>
<section id="t-test-1" class="level4">
<h4 class="anchored" data-anchor-id="t-test-1">T-Test</h4>
<div class="cell-container"><div class="cell-decorator"><pre>In [12]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>chl_high2 <span class="ot">&lt;-</span> lakehuron_binned <span class="sc">%&gt;%</span> <span class="fu">filter</span>(temp_cat <span class="sc">==</span> <span class="st">"High"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(chlorophyll_a)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>chl_low2  <span class="ot">&lt;-</span> lakehuron_binned <span class="sc">%&gt;%</span> <span class="fu">filter</span>(temp_cat <span class="sc">==</span> <span class="st">"Low"</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(chlorophyll_a)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(chl_high2, chl_low2, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  chl_high2 and chl_low2
t = 2.4774, df = 48.669, p-value = 0.01676
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
  1.06416 10.21513
sample estimates:
mean of x mean of y 
 16.12000  10.48036 </code></pre>
</div>
</div></div>
<div class="cell-container"><div class="cell-decorator"><pre>In [13]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>chl_comparison <span class="ot">&lt;-</span> lakehuron_binned <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(temp_cat <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"High"</span>))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chl_comparison, <span class="fu">aes</span>(<span class="at">x =</span> temp_cat, <span class="at">y =</span> chlorophyll_a, <span class="at">fill =</span> temp_cat)) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.15</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Low"</span> <span class="ot">=</span> <span class="st">"#56B1F7"</span>, <span class="st">"High"</span> <span class="ot">=</span> <span class="st">"#E76F51"</span>)) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Chlorophyll-a Levels by Surface Temperature Category in Lake Huron"</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Welch Two-Sample t-test: High vs Low Temperature"</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Surface Temperature Category"</span>,</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Chlorophyll-a (µg/L)"</span>,</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Temperature Category"</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="">
<figure class="figure">
<p class=""><a href="index_files/figure-html/unnamed-chunk-13-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div></div>
<p><strong>Figure 8:</strong> Graph showing the relationship between high and low temperature and chlorophyll A levels in Lake Huron.</p>
</section>
</section>
<section id="wilcox-tests" class="level3">
<h3 class="anchored" data-anchor-id="wilcox-tests">Wilcox Tests</h3>
<section id="chlorophyll-a-levels-at-high-temperatures-in-both-lakes" class="level4">
<h4 class="anchored" data-anchor-id="chlorophyll-a-levels-at-high-temperatures-in-both-lakes">Chlorophyll A Levels at High Temperatures in both Lakes</h4>
<div class="cell-container"><div class="cell-decorator"><pre>In [14]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(chl_high, chl_high2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  chl_high and chl_high2
W = 1458.5, p-value = 0.01907
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div></div>
<div class="cell-container"><div class="cell-decorator"><pre>In [15]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>chl_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">factor</span>(</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Lake Erie"</span>, <span class="fu">length</span>(chl_high)), <span class="fu">rep</span>(<span class="st">"Lake Huron"</span>, <span class="fu">length</span>(chl_high2))),</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Lake Erie"</span>, <span class="st">"Lake Huron"</span>)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">chlorophyll_a =</span> <span class="fu">c</span>(chl_high, chl_high2)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chl_data, <span class="fu">aes</span>(<span class="at">x =</span> group, <span class="at">y =</span> chlorophyll_a, <span class="at">fill =</span> group)) <span class="sc">+</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">trim =</span> <span class="cn">FALSE</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Lake Erie"</span> <span class="ot">=</span> <span class="st">"#2196F3"</span>, <span class="st">"Lake Huron"</span> <span class="ot">=</span> <span class="st">"#FF7043"</span>)) <span class="sc">+</span></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Comparison of Chlorophyll-a at High Temperatures Between Lake Erie and Lake Huron"</span>,</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Wilcoxon Rank-Sum Test"</span>,</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Lake"</span>,</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Chlorophyll-a (µg/L)"</span></span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">9</span>) <span class="sc">+</span></span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="">
<figure class="figure">
<p class=""><a href="index_files/figure-html/unnamed-chunk-15-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="index_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div></div>
<p><strong>Figure 9:</strong> Graph comparing the chlorophyll A levels at high temperatures in both lakes.</p>
</section>
<section id="chlorophyll-a-levels-at-low-temperatures-in-both-lakes" class="level4">
<h4 class="anchored" data-anchor-id="chlorophyll-a-levels-at-low-temperatures-in-both-lakes">Chlorophyll A Levels at Low Temperatures in both Lakes</h4>
<div class="cell-container"><div class="cell-decorator"><pre>In [16]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(chl_low, chl_low2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  chl_low and chl_low2
W = 1281, p-value = 0.421
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div></div>
<div class="cell-container"><div class="cell-decorator"><pre>In [17]:</pre></div><div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>chl_data2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="fu">factor</span>(</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"Lake Erie"</span>, <span class="fu">length</span>(chl_low)), <span class="fu">rep</span>(<span class="st">"Lake Huron"</span>, <span class="fu">length</span>(chl_low2))),</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Lake Erie"</span>, <span class="st">"Lake Huron"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">chlorophyll_a =</span> <span class="fu">c</span>(chl_low, chl_low2)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(chl_data2, <span class="fu">aes</span>(<span class="at">x =</span> group, <span class="at">y =</span> chlorophyll_a, <span class="at">fill =</span> group)) <span class="sc">+</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">trim =</span> <span class="cn">FALSE</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">outlier.shape =</span> <span class="cn">NA</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Lake Erie"</span> <span class="ot">=</span> <span class="st">"#2196F3"</span>, <span class="st">"Lake Huron"</span> <span class="ot">=</span> <span class="st">"#FF7043"</span>)) <span class="sc">+</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Comparison of Chlorophyll-a at Low Temperatures Between Lake Erie and Lake Huron"</span>,</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Wilcoxon Rank-Sum Test"</span>,</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Lake"</span>,</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Chlorophyll-a (µg/L)"</span></span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">9</span>) <span class="sc">+</span></span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)</span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="">
<figure class="figure">
<p class=""><a href="index_files/figure-html/unnamed-chunk-17-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="index_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div></div>
<p><strong>Figure 10:</strong> Graph comparing the chlorophyll A levels at low temperatures in both lakes.</p>
<p>The Chi squared test that was done on the Lake Erie data (dataset 1), the p value came back as 1.509e-07. This means that there is a significant relationship between temperature and chlorophyll A levels in Lake Erie. The Pearson correlation test that was performed on the data came back with a p value of 3.013e-10. This also shows a highly significant relationship between temperature and chlorophyll A levels, which is shown in Figure 5. The T-test done also came back with a very low p value of 3.669e-16. This test also shows a high significance in the relationship of the variables. In Figure 6, the strong relationship is shown in the graph. All of these highly statistically significant results mean that high temperature has a strong relationship with chlorophyll A levels. This indicates that there is a strong relation between temperature and primary productivity in Lake Erie.</p>
<p>The Chi squared test that was performed on the Lake Huron data (dataset 2) the p value came back as 0.03894. This means that the data is significant and there is a relation in this data of temperature to chlorophyll A levels. The Pearson correlation test that was done on the Lake Huron data had a p value of 0.1028. This also shows that there is not a significant linear relationship between temperature and chlorophyll A levels in Lake Huron, which is shown in Figure 7. The T-test that was done on the data came back with a p value of 0.01676. This shows that there is a significant relationship between the two variables in Lake Huron in this test, which is shown in Figure 8. These statistically significant relationships show that there is a correlation between temperature and chlorophyll A levels. These statistical tests showed that there is a relationship between primary productivity and temperature, but it was not as strong of a relationship as it was in Lake Erie.</p>
<p>The last tests that were done were Wilcox tests on the chlorophyll A levels when the temperature is high and low in each of the lakes. The first test was on the high temperature chlorophyll A levels being compared in the lakes, which came back with a p value of 0.01907. This shows that there is a significant relationship between the two lakes’ chlorophyll A levels, as you can see in Figure 9. The next test was on the low temperature chlorophyll A levels being compared in the lakes, which came back with a p value of 0.421. This shows an insignificant relationship between the chlorophyll A levels in the lakes. Figure 10 shows that there is much more variation in the levels of chlorophyll A at low temperatures than in high temperatures.</p>
</section>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>The Lake Erie dataset showed much stronger and consistent correlation between temperature and Chlorophyll A levels. This indicates there is a high significance in the relationship between variables and chlorophyll A levels are highly dependent on temperature. For the Lake Huron dataset, the p-value for the chi-squared test came back as significant while the value for the Pearson Correlation test indicates there was not a significant relationship between temperature and chlorophyll A. Since a chi-test measures association between categorical variables, continuous data is sorted into categories. This suggests there is a non-random association between the categories (high temperature and high chlorophyll A concentration for example). The Pearson correlation tests the strength and direction of the linear relationship between two continuous variables. This indicates that the relationship may not be linear, but could be curved, thresholded or influenced by other variables the Pearson Correlation test cannot detect.</p>
<p>These findings imply that temperature and chlorophyll A have a positive identifiable correlation. Since chlorophyll A is an indicator of high levels of algae productivity, this suggests that when temperatures increase, algal blooms also increase. Large algal blooms can be detrimental to lake ecosystem health. It is helpful to study this relationship because as temperatures increase with climate change, this might increase the level of harmful algal blooms in lake ecosystems. This could influence management decisions and the regulation of pollutants or nutrient input to the great lakes.&nbsp;</p>
<p>One possible reason for why Lake Erie had much stronger results for temperature and chlorophyll A levels is because it is the most polluted lake of the Great Lakes (<span class="citation" data-cites="wood1968pollution">Wood (<a href="#ref-wood1968pollution" role="doc-biblioref">1968</a>)</span>). Because it is more polluted than other lakes, it is more susceptible to eutrophication. Eutrophication in lakes occurs when there is an offloading of nutrients into the lake which feeds the algae there, causing large, harmful blooms. This usually comes from agricultural runoff from the fertilizer that is used. Lake Erie is particularly vulnerable to this happening quicker because it has much less volume than other Great Lakes (<span class="citation" data-cites="wood1968pollution">Wood (<a href="#ref-wood1968pollution" role="doc-biblioref">1968</a>)</span>). Lake Erie also has much more agricultural runoff coming into it (<span class="citation" data-cites="watson2016re">Watson et al. (<a href="#ref-watson2016re" role="doc-biblioref">2016</a>)</span>). This makes it much more vulnerable to large algal growths that can be harmful to the lake ecosystem’s health.</p>
<p>Another reason why Lake Erie had much stronger results is because there were several more points of data that were collected and used in the analysis. As you can see in Figures 5 and 6, there are several points of data and in Figures 7 and 8, there are far less than the previous ones. This could have created more variation in the results since there are less points of data. This could have caused it to be less precise with more room for error. This room for error is displayed the most in Figures 9 and 10, because the bubble around the box plot for Lake Huron that is representing the standard of error is much wider than Lake Erie’s. The difference in the number of data points is also very clear in these two figures because side by side there is a very clear disparity in the number of data points in Lake Erie and Lake Huron.</p>
<p>This analysis is very limited because the data used in these statistical tests were collected only during one year. This means that these statistical tests did not account for variation of different factors between years such as climate, nutrient input, and other factors. There was also a fairly small sample size which could have skewed the results. The next steps proposed are to conduct a much longer term study that spans multiple years to account for the variation between years and measure how increasing temperatures are changing chlorophyll A concentration. Using different study sites on different lakes or different parts of the lakes could also give a more comprehensive picture of this relationship.</p>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-baker2004chlorophyll" class="csl-entry" role="listitem">
Baker, N. R., &amp; Oxborough, K. (2004). Chlorophyll fluorescence as a probe of photosynthetic productivity. In <em>Chlorophyll a fluorescence: A signature of photosynthesis</em> (pp. 65–82). Springer.
</div>
<div id="ref-bjorn2009viewpoint" class="csl-entry" role="listitem">
Björn, L. O., Papageorgiou, G. C., Blankenship, R. E., &amp; Govindjee. (2009). A viewpoint: Why chlorophyll a? <em>Photosynthesis Research</em>, <em>99</em>, 85–98.
</div>
<div id="ref-dunstan2018global" class="csl-entry" role="listitem">
Dunstan, P. K., Foster, S. D., King, E., Risbey, J., O’Kane, T. J., Monselesan, D., Hobday, A. J., Hartog, J. R., &amp; Thompson, P. A. (2018). Global patterns of change and variation in sea surface temperature and chlorophyll a. <em>Scientific Reports</em>, <em>8</em>(1), 14624.
</div>
<div id="ref-mishra2010review" class="csl-entry" role="listitem">
Mishra, A. K., &amp; Singh, V. P. (2010). A review of drought concepts. <em>Journal of Hydrology</em>, <em>391</em>(1-2), 202–216.
</div>
<div id="ref-o2017anthropogenic" class="csl-entry" role="listitem">
O’Beirne, M., Werne, J., Hecky, R., Johnson, T., Katsev, S., &amp; Reavie, E. D. (2017). Anthropogenic climate change has altered primary productivity in lake superior. <em>Nature Communications</em>, <em>8</em>(1), 15713.
</div>
<div id="ref-qian2021chlorophyll" class="csl-entry" role="listitem">
Qian, S. S., Stow, C. A., Rowland, F. E., Liu, Q., Rowe, M. D., Anderson, E. J., Stumpf, R. P., &amp; Johengen, T. H. (2021). Chlorophyll a as an indicator of microcystin: Short-term forecasting and risk assessment in lake erie. <em>Ecological Indicators</em>, <em>130</em>, 108055.
</div>
<div id="ref-shi2023impacts" class="csl-entry" role="listitem">
Shi, X., Yu, H., Zhao, S., Sun, B., Liu, Y., Huo, J., Wang, S., Wang, J., Wu, Y., Wang, Y., et al. (2023). Impacts of environmental factors on chlorophyll-a in lakes in cold and arid regions: A 10-year study of wuliangsuhai lake, china. <em>Ecological Indicators</em>, <em>148</em>, 110133.
</div>
<div id="ref-lakehuron" class="csl-entry" role="listitem">
US Department of Commerce, N. (n.d.-a). NOAA-glerl saginaw bay sampling data. In <em>Home: NOAA Great Lakes Environmental Research Laboratory - Ann Arbor, MI, USA</em>. <a href="https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/sb-weekly-current/">https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/sb-weekly-current/</a>
</div>
<div id="ref-lakeerie" class="csl-entry" role="listitem">
US Department of Commerce, N. (n.d.-b). NOAA-glerl western lake erie sampling data. In <em>Home: NOAA Great Lakes Environmental Research Laboratory - Ann Arbor, MI, USA</em>. <a href="https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/wle-weekly-current/">https://www.glerl.noaa.gov/res/HABs_and_Hypoxia/wle-weekly-current/</a>
</div>
<div id="ref-watson2016re" class="csl-entry" role="listitem">
Watson, S. B., Miller, C., Arhonditsis, G., Boyer, G. L., Carmichael, W., Charlton, M. N., Confesor, R., Depew, D. C., Höök, T. O., Ludsin, S. A., et al. (2016). The re-eutrophication of lake erie: Harmful algal blooms and hypoxia. <em>Harmful Algae</em>, <em>56</em>, 44–66.
</div>
<div id="ref-wood1968pollution" class="csl-entry" role="listitem">
Wood, K. G. (1968). Pollution and lake erie. <em>Bios</em>, 103–110.
</div>
<div id="ref-singh" class="csl-entry" role="listitem">
Wurtsbaugh, W. A., Paerl, H. W., &amp; Dodds, W. K. (2019). Nutrients, eutrophication and harmful algal blooms along the freshwater to marine continuum. <em>WIREs Water</em>, <em>6</em>(5), e1373. https://doi.org/<a href="https://doi.org/10.1002/wat2.1373">https://doi.org/10.1002/wat2.1373</a>
</div>
</div>
</section>
     </main>
<!-- /main column -->  <script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>  </div> <!-- /content -->  <script>var lightboxQuarto = GLightbox({"selector":".lightbox","descPosition":"bottom","openEffect":"zoom","closeEffect":"zoom","loop":false});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script> 
  
</body></html>